#!/bin/bash

if [ "$(basename $(pwd))" != "build-scripts" ]; then
    echo "You must be in build-scripts to run this script"
    exit -1
fi

job_count=`nproc`
if [ "$1" == "-1" ]; then
    job_count=1
    shift
fi

./configure-debug "$@"

cmake --build ../build --target all --config Debug -- -j$job_count