#!/bin/bash

if [ "$(basename $(pwd))" != "build-scripts" ]; then
    echo "You must be in build-scripts to run this script"
    exit -1
fi

cmake -H../ -B../build -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_BUILD_TYPE=Debug "$@"
